### ISSUE TITLE
Junit Soft Assertions: watcher always succeed

### ISSUE THREAD

**Issue by Sarute** [joel-costigliola/assertj-core#470] opened 2015-07-21 11:06 UTC
Hi! I have a problem with a personalize test watcher which does not recognize failed junit soft assertions . 
In my test class, I have defined:

@Rule public TestWatcherJunit tWatcher = new TestWatcherJunit(driver);
@Rule public final UiObjectPredicateJUnitSoft softly = new UiObjectPredicateJUnitSoft();
.....
softly.assertThat(labelFor).containsAll(inputId);

If I run:
 assertThat(labelFor).containsAll(inputId); --> test Watcher calls method failed (it should fail)

If I run:
 softy-assertThat(labelFor).containsAll(inputId); --> test Watcher calls method succeeded .... Why?

Thank you very much.

**Comment by joel-costigliola** [comment] 2015-07-21 11:11
Hi Sarute,
What is the result if you don't use `TestWatcherJunit` ? 
Can you provide a full test case, so that I can reproduce the problem ? 
Cheers

**Comment by Sarute** [comment] 2015-07-21 12:20
I forgot to tell you...
Eclipse recognized that the test fails, 
![schermata 2015-07-21 alle 14 16 28](https://cloud.githubusercontent.com/assets/1528200/8800448/19694c62-2fb3-11e5-81d4-0c9336e7d2e8.png)
it's just my TestWatcherJUnit that does not. 
![schermata 2015-07-21 alle 14 15 34](https://cloud.githubusercontent.com/assets/1528200/8800445/15ed4eda-2fb3-11e5-86b9-73b3c391c751.png)

I don't know if I can extract just a test case, since I have a lot of customized classes,
but I will try.

**Comment by Sarute** [comment] 2015-07-21 13:54
Test Case:
```
import java.io.IOException;
import org.assertj.core.api.JUnitSoftAssertions;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
import org.junit.rules.TestWatcher;
import org.junit.runner.RunWith;
import it.ids.testHarness.genericTH.SUT;
import it.ids.testHarness.genericTH.THFactory;
import it.ids.testHarness.genericTH.TestHarnessException;
import it.ids.testHarness.genericTH.TestWatcherSoftlyTests;
import it.ids.testHarness.genericTH.reporter.Recorders;
import junitparams.JUnitParamsRunner;

@RunWith(JUnitParamsRunner.class)
public class TestSoftly{	
	static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger( SUT.loggerName );

	@Rule public TestName name = new TestName();
	@Rule public TestWatcher tWatcher = new TestWatcherSoftlyTests();
	@Rule public final JUnitSoftAssertions softly = new JUnitSoftAssertions();

	@BeforeClass
	public static void setUpSUT() throws TestHarnessException, IOException{
		Recorders.register(THFactory.createHtml5Recorder());
		Recorders.recordStartSuite("TestCercapersone");
	}

	@AfterClass
	public static void tearDownDriver() throws Exception {
		Recorders.recordEndSuite();
	}

	@Test
	public void softAssertion_shouldFail() throws Exception{
		String descrizione = "Try";
		Recorders.recordStartTest(name.getMethodName(), descrizione);
		softly.assertThat(true).isFalse();
	}

}
```

MyTestWatcher:
```
public class TestWatcherSoftlyTests extends TestWatcher {
    private long startTime;
    private long endTime; 
	private BrowserDriver driver;

	public TestWatcherSoftlyTests() {
	}
	
	/**
	 * @param d
	 * @return: the qualified name of the current test method
	 */
	protected String getTestName(Description d){
		return String.format("%s.%s",d.getClassName(),d.getMethodName());
	}
	
	@Override
	protected void starting(Description d) {
		startTime = System.currentTimeMillis();
	}

	@Override
	protected void succeeded(Description d) {
		System.out.print(String.format("SUCCEED!!!! %n"));
	}

	@Override
	protected void failed(Throwable e, Description d) {
		System.out.print(String.format("FAILED!!!! %n"));

	}

	@Override
	protected void finished(Description d) {
		endTime = System.currentTimeMillis();
		System.out.print(String.format("FINISHED!!!! %n"));
	}
  	
  }
```
Expected Result Console:
FAILED!!!!
FINISHED!!!

Actual Result Console:
![schermata 2015-07-21 alle 15 52 20](https://cloud.githubusercontent.com/assets/1528200/8802245/80b613a2-2fc0-11e5-9af8-dff2b891ece7.png)


Thank you

**Comment by joel-costigliola** [comment] 2015-07-21 22:56
If the test fails as expected in eclipse then I think the problem is in `TestWatcherJunit`, not in `JUnitSoftAssertions`.
I can't really do any investigation, but my guts feeling is that `TestWatcherJunit` rule might be called before `JUnitSoftAssertions` one, in that case `TestWatcherJunit` does not see any error as errors have not yet been evaluated by  `JUnitSoftAssertions`.
I'm pretty sure that if you used the basic soft assertions (where you need to call `softly.assertAll()`) you would see `TestWatcherJunit` reporting errors correctly.

That was my 2cts, can't do more than that unfortunately.

I'm closing the issue as it is not an AssertJ problem, but feel free to prove me wrong and I'll reopen it.

**Closed by joel-costigliola** 2015-07-21 22:56 UTC

**Comment by Sarute** [comment] 2015-07-22 06:48
With basic soft assertions it works! :)
Thank you very much for your support!
