### ISSUE TITLE
[AssertJ Core 1.6.1 / 1.7.1]  - asserts using isEqualToIgnoringGivenFields or isEqualToComparingFieldByField doesnt work properly

### ISSUE THREAD

**Issue by otoniel-isidoro-sofist** [joel-costigliola/assertj-core#425] opened 2015-05-29 18:42 UTC
I am using assertj-android (https://github.com/square/assertj-android) that is using asserj-core 1.6.1  and I have the following objects:

actual:

UserInfo{userId='97ed99c1-13d9-4886-99f0-15e3e309bfac', appInstallId='f9d6abaf-e3e4-4281-9ad2-9d8083bd5936', scenarioId=18, advertisingId='803cef82-00af-4c0d-b76e-4f438118ec71', androidId='5ec1103ef436f4f6', imei='null', pushToken='null', platformAccountEmail='[]', deviceSystemName='ANDROID', deviceSystemVersion='5.1', deviceCountry='US', deviceLanguage='en', deviceTimezone='-3', deviceManufacturer='unknown', deviceModel='Android SDK built for x86', appInstalledAt=1432823697421, appVersion='0.11.3', appSdkVersion='0.11.4', tags=null}

expected:
UserInfo{userId='97ed99c1-13d9-4886-99f0-15e3e309bfac', appInstallId='f9d6abaf-e3e4-4281-9ad2-9d8083bd5936', scenarioId=17, advertisingId='803cef82-00af-4c0d-b76e-4f438118ec71', androidId='5ec1103ef436f4f6', imei='null', pushToken='APA91bE_u2RlHz9HmiK68-RQfZcDTU_Wzsf7xZgYPp4orGmsrs5uXZ1tmE56TsPiqxfUtGuAxRTuayC0_vmeLiyATEJNaG8z_i6RdP9Oj-rD2zyJp6pFduBrvdO6gjJgAHLup5V5WVIFKzGIkZ3wyBG3WNvKc9Ecpg', platformAccountEmail='[]', deviceSystemName='ANDROID', deviceSystemVersion='5.1', deviceCountry='US', deviceLanguage='en', deviceTimezone='-3', deviceManufacturer='unknown', deviceModel='Android SDK built for x86', appInstalledAt=1432823697421, appVersion='0.11.3', appSdkVersion='0.11.4', tags=null}

When I use isEqualTo assertions the following failure is threw properly:
org.junit.ComparisonFailure: expected:<...d5936', scenarioId=3[3, advertisingId='803cef82-00af-4c0d-b76e-4f438118ec71', androidId='5ec1103ef436f4f6', imei='null', pushToken='APA91bE_u2RlHz9HmiK68-RQfZcDTU_Wzsf7xZgYPp4orGmsrs5uXZ1tmE56TsPiqxfUtGuAxRTuayC0_vmeLiyATEJNaG8z_i6RdP9Oj-rD2zyJp6pFduBrvdO6gjJgAHLup5V5WVIFKzGIkZ3wyBG3WNvKc9Ecpg]', platformAccountEm...> but was:<...d5936', scenarioId=3[4, advertisingId='803cef82-00af-4c0d-b76e-4f438118ec71', androidId='5ec1103ef436f4f6', imei='null', pushToken='null]', platformAccountEm...>

But, when I use isEqualToComparingFieldByField or isEqualToIgnoringGivenFields the test pass even with different values on object's fields.

I already tried replace 1.6.1 with the newest version supported for android (1.7.1) and the same problem occurs.

Is this a problem with 1.x versions?

**Comment by AlexBischof** [comment] 2015-05-29 20:38
Have you seen the following part in the Javadoc?
```
Note that only <b>accessible </b>fields values are compared, accessible fields include directly accessible fields (e.g. public) or fields with an accessible getter.
```

It looks like your *UserInfo* class does not fit the requirements.

With the following code i could reproduce the behavior.
```java
static class Person {
        private String name;
        private int age;
        private Object whatever;

        Person(String name, int age, Object whatever) {
            this.name = name;
            this.age = age;
            this.whatever = whatever;
        }

        //MISSING
        //public String getName() {return name;}
        //public int getAge() {return age;}
        //public Object getWhatever() {return whatever;}
    }

    public static void main(String[] args) {
        Person alex = new Person("Alex", 34, "HelloWorld");
        Person luke = new Person("Luke", 21, null);

        assertThat(alex).isEqualTo(luke);
        assertThat(alex).isEqualToComparingFieldByField(luke);
    }
```

**Comment by joel-costigliola** [comment] 2015-05-29 22:31
assertj-core 2.0 can compare private fields but unfortunately it is not compatible with android due to `Path` dependency.

**Comment by joel-costigliola** [comment] 2015-05-29 22:32
@otoniel-isidoro-sofist please give us a test case showing the problem with code we can run.

**Comment by otoniel-isidoro-sofist** [comment] 2015-05-30 01:37
@AlexBischof thanks for the reply but my object has the public getters as you can see below:
```java

/**
 * UserInfo visible to the user.
 *
 */
@Keep
@KeepClassMemberNames
public class UserInfo implements Serializable {

    private static final long serialVersionUID = 2549312506185234639L;

    private String userId;
    private String appInstallId;
    private Long scenarioId;

    /* user info */
    private String advertisingId;
    private String androidId;
    private String imei;
    private String pushToken;
    private String platformAccountEmail;

    /* device info */
    private String deviceSystemName;
    private String deviceSystemVersion;
    private String deviceCountry;
    private String deviceLanguage;
    private String deviceTimezone;
    private String deviceManufacturer;
    private String deviceModel;

    /* app info */
    private Long appInstalledAt;
    private String appVersion;
    private String appSdkVersion;

    private Set<String> tags;

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getAppInstallId() {
        return appInstallId;
    }

    public void setAppInstallId(String appInstallId) {
        this.appInstallId = appInstallId;
    }

    public Long getScenarioId() {
        return scenarioId;
    }

    public void setScenarioId(Long scenarioId) {
        this.scenarioId = scenarioId;
    }

    public String getAdvertisingId() {
        return advertisingId;
    }

    public void setAdvertisingId(String advertisingId) {
        this.advertisingId = advertisingId;
    }

    public String getAndroidId() {
        return androidId;
    }

    public void setAndroidId(String androidId) {
        this.androidId = androidId;
    }

    public String getImei() {
        return imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

    public String getPushToken() {
        return pushToken;
    }

    public void setPushToken(String pushToken) {
        this.pushToken = pushToken;
    }

    public String getDeviceSystemName() {
        return deviceSystemName;
    }

    public void setDeviceSystemName(String deviceSystemName) {
        this.deviceSystemName = deviceSystemName;
    }

    public String getDeviceSystemVersion() {
        return deviceSystemVersion;
    }

    public void setDeviceSystemVersion(String deviceSystemVersion) {
        this.deviceSystemVersion = deviceSystemVersion;
    }

    public String getDeviceCountry() {
        return deviceCountry;
    }

    public void setDeviceCountry(String deviceCountry) {
        this.deviceCountry = deviceCountry;
    }

    public String getDeviceLanguage() {
        return deviceLanguage;
    }

    public void setDeviceLanguage(String deviceLanguage) {
        this.deviceLanguage = deviceLanguage;
    }

    public String getDeviceTimezone() {
        return deviceTimezone;
    }

    public void setDeviceTimezone(String deviceTimezone) {
        this.deviceTimezone = deviceTimezone;
    }

    public String getDeviceManufacturer() {
        return deviceManufacturer;
    }

    public void setDeviceManufacturer(String deviceManufacturer) {
        this.deviceManufacturer = deviceManufacturer;
    }

    public String getDeviceModel() {
        return deviceModel;
    }

    public void setDeviceModel(String deviceModel) {
        this.deviceModel = deviceModel;
    }

    public Long getAppInstalledAt() {
        return appInstalledAt;
    }

    public void setAppInstalledAt(Long appInstalledAt) {
        this.appInstalledAt = appInstalledAt;
    }

    public String getAppVersion() {
        return appVersion;
    }

    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion;
    }

    public String getAppSdkVersion() {
        return appSdkVersion;
    }

    public void setAppSdkVersion(String appSdkVersion) {
        this.appSdkVersion = appSdkVersion;
    }

    public Set<String> getTags() {
        return tags;
    }

    public void setTags(Set<String> tags) {
        this.tags = tags;
    }

    public String getPlatformAccountEmail() {
        return platformAccountEmail;
    }

    public void setPlatformAccountEmail(String platformAccountEmail) {
        this.platformAccountEmail = platformAccountEmail;
    }

    @Override
    public String toString() {
        return "UserInfo{" +
                "userId='" + userId + '\'' +
                ", appInstallId='" + appInstallId + '\'' +
                ", scenarioId=" + scenarioId +
                ", advertisingId='" + advertisingId + '\'' +
                ", androidId='" + androidId + '\'' +
                ", imei='" + imei + '\'' +
                ", pushToken='" + pushToken + '\'' +
                ", platformAccountEmail='" + platformAccountEmail + '\'' +
                ", deviceSystemName='" + deviceSystemName + '\'' +
                ", deviceSystemVersion='" + deviceSystemVersion + '\'' +
                ", deviceCountry='" + deviceCountry + '\'' +
                ", deviceLanguage='" + deviceLanguage + '\'' +
                ", deviceTimezone='" + deviceTimezone + '\'' +
                ", deviceManufacturer='" + deviceManufacturer + '\'' +
                ", deviceModel='" + deviceModel + '\'' +
                ", appInstalledAt=" + appInstalledAt +
                ", appVersion='" + appVersion + '\'' +
                ", appSdkVersion='" + appSdkVersion + '\'' +
                ", tags=" + tags +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UserInfo)) return false;

        UserInfo userInfo = (UserInfo) o;

        if (getUserId() != null ? !getUserId().equals(userInfo.getUserId()) : userInfo.getUserId() != null)
            return false;
        if (getAppInstallId() != null ? !getAppInstallId().equals(userInfo.getAppInstallId()) : userInfo.getAppInstallId() != null)
            return false;
        if (getScenarioId() != null ? !getScenarioId().equals(userInfo.getScenarioId()) : userInfo.getScenarioId() != null)
            return false;
        if (getAdvertisingId() != null ? !getAdvertisingId().equals(userInfo.getAdvertisingId()) : userInfo.getAdvertisingId() != null)
            return false;
        if (getAndroidId() != null ? !getAndroidId().equals(userInfo.getAndroidId()) : userInfo.getAndroidId() != null)
            return false;
        if (getImei() != null ? !getImei().equals(userInfo.getImei()) : userInfo.getImei() != null)
            return false;
        if (getPushToken() != null ? !getPushToken().equals(userInfo.getPushToken()) : userInfo.getPushToken() != null)
            return false;
        if (getPlatformAccountEmail() != null ? !getPlatformAccountEmail().equals(userInfo.getPlatformAccountEmail()) : userInfo.getPlatformAccountEmail() != null)
            return false;
        if (getDeviceSystemName() != null ? !getDeviceSystemName().equals(userInfo.getDeviceSystemName()) : userInfo.getDeviceSystemName() != null)
            return false;
        if (getDeviceSystemVersion() != null ? !getDeviceSystemVersion().equals(userInfo.getDeviceSystemVersion()) : userInfo.getDeviceSystemVersion() != null)
            return false;
        if (getDeviceCountry() != null ? !getDeviceCountry().equals(userInfo.getDeviceCountry()) : userInfo.getDeviceCountry() != null)
            return false;
        if (getDeviceLanguage() != null ? !getDeviceLanguage().equals(userInfo.getDeviceLanguage()) : userInfo.getDeviceLanguage() != null)
            return false;
        if (getDeviceTimezone() != null ? !getDeviceTimezone().equals(userInfo.getDeviceTimezone()) : userInfo.getDeviceTimezone() != null)
            return false;
        if (getDeviceManufacturer() != null ? !getDeviceManufacturer().equals(userInfo.getDeviceManufacturer()) : userInfo.getDeviceManufacturer() != null)
            return false;
        if (getDeviceModel() != null ? !getDeviceModel().equals(userInfo.getDeviceModel()) : userInfo.getDeviceModel() != null)
            return false;
        if (getAppInstalledAt() != null ? !getAppInstalledAt().equals(userInfo.getAppInstalledAt()) : userInfo.getAppInstalledAt() != null)
            return false;
        if (getAppVersion() != null ? !getAppVersion().equals(userInfo.getAppVersion()) : userInfo.getAppVersion() != null)
            return false;
        if (getAppSdkVersion() != null ? !getAppSdkVersion().equals(userInfo.getAppSdkVersion()) : userInfo.getAppSdkVersion() != null)
            return false;
        return !(getTags() != null ? !getTags().equals(userInfo.getTags()) : userInfo.getTags() != null);

    }

    @Override
    public int hashCode() {
        int result = getUserId() != null ? getUserId().hashCode() : 0;
        result = 31 * result + (getAppInstallId() != null ? getAppInstallId().hashCode() : 0);
        result = 31 * result + (getScenarioId() != null ? getScenarioId().hashCode() : 0);
        result = 31 * result + (getAdvertisingId() != null ? getAdvertisingId().hashCode() : 0);
        result = 31 * result + (getAndroidId() != null ? getAndroidId().hashCode() : 0);
        result = 31 * result + (getImei() != null ? getImei().hashCode() : 0);
        result = 31 * result + (getPushToken() != null ? getPushToken().hashCode() : 0);
        result = 31 * result + (getPlatformAccountEmail() != null ? getPlatformAccountEmail().hashCode() : 0);
        result = 31 * result + (getDeviceSystemName() != null ? getDeviceSystemName().hashCode() : 0);
        result = 31 * result + (getDeviceSystemVersion() != null ? getDeviceSystemVersion().hashCode() : 0);
        result = 31 * result + (getDeviceCountry() != null ? getDeviceCountry().hashCode() : 0);
        result = 31 * result + (getDeviceLanguage() != null ? getDeviceLanguage().hashCode() : 0);
        result = 31 * result + (getDeviceTimezone() != null ? getDeviceTimezone().hashCode() : 0);
        result = 31 * result + (getDeviceManufacturer() != null ? getDeviceManufacturer().hashCode() : 0);
        result = 31 * result + (getDeviceModel() != null ? getDeviceModel().hashCode() : 0);
        result = 31 * result + (getAppInstalledAt() != null ? getAppInstalledAt().hashCode() : 0);
        result = 31 * result + (getAppVersion() != null ? getAppVersion().hashCode() : 0);
        result = 31 * result + (getAppSdkVersion() != null ? getAppSdkVersion().hashCode() : 0);
        result = 31 * result + (getTags() != null ? getTags().hashCode() : 0);
        return result;
    }
}
``` 
@joel-costigliola I will create a project to exemplify the problem because the actual code that I am working is private. Thanks for the quick reply too.

**Comment by AlexBischof** [comment] 2015-05-30 07:37
Thank you for providing the *UserInfo* class, looks normal and works in my tests as expected in 2.0.0 as well as in 1.7.1.

Btw the failure message of the isEqualTo looks a little bit strange considering the scenarioId which should only a number string. But it seems that it contains *scenarioId* + *String of another* userinfo, isn't it?

**Comment by joel-costigliola** [comment] 2015-06-07 05:46
Closing the issue as not reproducible.
@otoniel-isidoro-sofist feel free to comment on this issue even if it is closed, I will reopen it if you can provide a test case.

**Closed by joel-costigliola** 2015-06-07 05:46 UTC
