### ISSUE TITLE
`NullPointerException` in `isEqualTo` assertion

### ISSUE THREAD

**Issue by Turbo87** [joel-costigliola/assertj-core#1440] opened 2019-02-18 08:02 UTC
#### Summary

see https://github.com/Turbo87/intellij-emberjs/pull/246

```
java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
        at java.util.regex.Matcher.reset(Matcher.java:309)
        at java.util.regex.Matcher.<init>(Matcher.java:229)
        at java.util.regex.Pattern.matcher(Pattern.java:1093)
        at java.util.Formatter.parse(Formatter.java:2547)
        at java.util.Formatter.format(Formatter.java:2501)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at org.assertj.core.api.AbstractStringAssert.isEqualTo(AbstractStringAssert.java:310)
        at org.assertj.core.api.StringAssert$ByteBuddy$gUBfusQU.isEqualTo$accessor$e5ipmL7L(Unknown Source)
        at org.assertj.core.api.StringAssert$ByteBuddy$gUBfusQU$AssertJ$SoftProxies$xRrT7HuB.call(Unknown Source)
        at org.assertj.core.api.ErrorCollector.intercept(ErrorCollector.java:58)
        at org.assertj.core.api.StringAssert$ByteBuddy$gUBfusQU.isEqualTo(Unknown Source)
        at org.assertj.core.api.StringAssert$ByteBuddy$gUBfusQU.isEqualTo(Unknown Source)
```

**Comment by joel-costigliola** [comment] 2019-02-18 08:39
thanks for reporting this, could you provide a test case for it ?

**Comment by Turbo87** [comment] 2019-02-18 09:21
https://github.com/Turbo87/intellij-emberjs/blob/d526a6ca4974bace1d3ca396a3be57961bb0108e/src/test/kotlin/com/emberjs/resolver/EmberNameTest.kt#L107-L109 is the code that seems to trigger this. I'm not sure yet what specifically is causing it though 🤔

**Comment by Turbo87** [comment] 2019-02-18 09:23
looking though the code, could it be that `.isEqualTo(null)` is the problem?

**Comment by joel-costigliola** [comment] 2019-02-18 09:27
I won't be able to look at the code until next week, could you print actual
and  expected to get more information?

**Comment by epeee** [comment] 2019-02-18 19:52
I just had a look at this one and it looks like this one only happens if assertj is used from Kotlin.
A simple example which reproduces this one:
```kotlin
    @Test
    fun `should pass`() {
        assertThat("test").isEqualTo(null)
    }
```
As shown in the provided stacktrace we end up in:

https://github.com/joel-costigliola/assertj-core/blob/2c57b2b4e470a0a7ff50ee64cbc7d27c02303893/src/main/java/org/assertj/core/api/AbstractStringAssert.java#L309-L311

We are heading into the nullpointer since `expectedStringTemplate` is null.

**Comment by joel-costigliola** [comment] 2019-02-18 20:11
interesting, why is Kotlin not resolving the method like java ?
is there something we can do?

**Comment by ming13** [comment] 2019-02-19 06:10
Same here.

```kotlin
val actualValue: String? = "value"
val expectedValue: String? = null

assertThat(actualValue).isEqualTo(expectedValue)
```

**Comment by ming13** [comment] 2019-02-19 06:14
Seems like it was introduced by #1425 in `3.12.0`. Looks like a reasonable issue though since `expectedStringTemplate` is `String` and `args` is an optional `vararg`. I would suggest to change the comparison logic to fallback to regular `isEqualsTo` when `expectedStringTemplate` is `null`.

**Comment by joel-costigliola** [comment] 2019-02-19 08:20
The real issue here is why kotlin is resolving `isEqualTo(String template, Object... args)` instead of `isEqualTo(Object expected)` ?

**Comment by joel-costigliola** [comment] 2019-02-19 08:22
@ming13 your suggestion would work for Kotlin users but it is not so nice for java users since if they provide a null template, this should be considered as an error and not as an intent to call `assertThat("test").isEqualTo(null)`.

**Comment by joel-costigliola** [comment] 2019-02-19 08:24
I can't verify it but this might be fixed by https://github.com/joel-costigliola/assertj-core/pull/1442

**Comment by joel-costigliola** [comment] 2019-02-19 08:31
I'm not strongly opinionated about my previous comment as I think this is an edge case but I'd really like to know if this was an intended Kotlin behavior (it's a bit weird for a language putting java compatibility as something important)

> @ming13 your suggestion would work for Kotlin users but it is not so nice for java users since if they provide a null template, this should be considered as an error and not as an intent to call `assertThat("test").isEqualTo(null)`.

**Comment by epeee** [comment] 2019-02-19 20:54
It looks like there are several discussions about topics like this one in jetbrains issue tracker: https://youtrack.jetbrains.com/issue/KT-3090

Currently, I see 3 possible solutions for this problem:

### 1. add 

```java
public SELF isEqualTo(String s) {
  return super.isEqualTo(s);
}
```
to `AbstractStringAssert`

### 2. the solution provided in the pr linked above
### 3. ask kotlin users to use
```kotlin
assertThat("test").isEqualTo(null as Any?)
```
  instead of
```kotlin
assertThat("test").isEqualTo(null)
```

**Comment by Turbo87** [comment] 2019-04-26 06:52
> I can't verify it but this might be fixed by #1442

I'm assuming that #1442 has been released by now, though unfortunately this did not seem to fix it. Our CI is still failing with the latest release (see https://github.com/Turbo87/intellij-emberjs/pull/249).

**Comment by joel-costigliola** [comment] 2019-04-26 10:12
@Turbo87  Nope it will be in 3.13.0, you can try to build 3.13.0-SNAPSHOT and give a try, I would appreciate to know if the fix works for you.

**Comment by tsollas** [comment] 2019-05-09 14:41
Essentially and in short, this issue is a symptom of Kotlin's differences in handling method overload resolutions with regards to varargs vs Java. Basically, isEqualTo(null) is calling with empty varargs from Kotlin, which resolves to the varargs version of isEqualTo, because empty varargs is still, well, valid varargs.

See: https://youtrack.jetbrains.com/issue/KT-3090 for related issues in Kotlin.

**Comment by joel-costigliola** [comment] 2019-05-12 04:03
closing as a duplicate of #1442 but will reopen it if proven wrong.

**Closed by joel-costigliola** 2019-05-12 04:03 UTC
