### ISSUE TITLE
"extracting" doesn't work as expected

### ISSUE THREAD

**Issue by eximius313** [joel-costigliola/assertj-core#1169] opened 2018-01-30 19:04 UTC
Having such test case:

```java
public class AssertJTest {

  public static class Tester {
    private String name;
  }

  public String nameProvider(final Tester tester) {
    return tester.name;
  }

  @Test
  public void shouldProperlyExtractString() {
    final Tester t = new Tester();
    t.name = "randomName";

    Assertions.assertThat(t)
      .extracting(this::nameProvider)
      .contains("random");
  }
}
```

fails with:
```
[error] Test AssertJTest.shouldProperlyExtractString failed:
[error] Expecting:
[error]  <["randomName"]>
[error] to contain:
[error]  <["random"]>
[error] but could not find:
[error]  <["random"]>
[error] , took 0.1 sec
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error]         AssertJTest
```

while:
```java
  @Test
  public void shouldProperlyContainString() {
    final Tester t = new Tester();
    t.name = "randomName";

    Assertions.assertThat(t.name)
      .contains("random");
  }
```
passes

**Comment by filiphr** [comment] 2018-01-30 19:26
@eximius313 this is actually correct. As you have 2 different context.

In your first example `assertThat(t).extracting(this::nameProvider)` returns `AbstractObjectArrayAssert` where `contains` checks if the array / list of extracted values contains the String `"random"`. Whereas `asserThat(t.name)` is `AbstractCharSequenceAssert` where `contains` check if the string under test contains `"random"`

**Comment by eximius313** [comment] 2018-01-30 20:19
But I'm exctracting *just one property*, using *just one function* (`Function<Tester,String>`), thus resulted Assert should be the one from Returning type (`<String>` in this case), so `AbstractCharSequenceAssert`

**Comment by joel-costigliola** [comment] 2018-01-30 20:33
Two things: 

- @filiphr is correct, the [`extracting`](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractObjectAssert.html#extracting-java.util.function.Function...-) javadoc also explains it.
- IMO `extracting` makes more sense when extracting multiple values, it was designed for that
- if we supported one value extraction as you expected, due to java generics limitations, it would not be  possible to return String assertions after extracting a String (believe when I say I wish it could be possible).

Since you extract only one value and wants strongly typed assertion, what you can do is:
```
assertThat(nameProvider(t)).contains("random");
```
Not sure if it will fulfill your real life requirements but at the moment that's the best you can do.

I'm closing this issue but feel free to continue the discussion.

**Closed by joel-costigliola** 2018-01-30 20:33 UTC

**Comment by eximius313** [comment] 2018-01-30 21:31
The thing is, that I have multiple assertions on several properties of **one object**.
I always feel bad when I see this:
```java
assertThat(result.status()).isEqualTo("OK");
assertThat(result.getSomething()).isEqualTo("aa");
assertThat(result.getName()).contains("name");
assertThat(result.other()).isNotNull();
```
that is why, I wanted to use something like this:
```java
assertThat(result)
      .matches(hasStatus("OK"))
      .hasFieldOrProperty("something", "aa");
      .extracting(Result::getName)
            .contains("name")
      .extracting(Result::other)
            .isNotNull();
```
so you say, that my version is not possible?

**Comment by joel-costigliola** [comment] 2018-01-30 21:44
short answer: no
long answer:
some of your assertions are not doing what you expect, for example `extracting(Result::other).isNotNull();` will always succeed as the result of extracting is a list and you are checking that the list is not null whereas you likely wanted to check that the other value was not null.

I don't see anything wrong with:
```
assertThat(result.status()).isEqualTo("OK");
assertThat(result.getSomething()).isEqualTo("aa");
assertThat(result.getName()).contains("name");
assertThat(result.other()).isNotNull();
```
I understand it is not as elegant as chaining assertions but IMO a better solution would be to write [custom assertions](http://joel-costigliola.github.io/assertj/assertj-core-custom-assertions.html) for result (it is worth it if you are asserting object of this type in multiple tests).
I would create custom assertions to be able to write something like:
```
assertThat(result).hasStatus("OK")
                  .hasSomething("aa")
                  .hasNameContaining("name")
                  .hasNonNullOther();
```
You can also play with Conditions, it is not as nice as custom assertions for readability but requires less work.
