### ISSUE TITLE
recursive comparison does not report missing fields correctly

### ISSUE THREAD

**Issue by Sam-Kruglov** [joel-costigliola/assertj-core#1579] opened 2019-08-18 05:39 UTC
If I compare recursively 2 objects with different sets of fields then I get this:
```
java.lang.AssertionError: 
Expecting:
  <SaveDataObjectCommand(id=MF_OMI:XXX-12, groupId=3ab62cd2-d924-4482-a986-d1e3dc2dcd22, propagated=false, idInSystem=XXX-12, systemName=MF_OMI, status=NEW, fields={field1=value1})>
to be equal to:
  <DataObjectCreatedEvent(groupId=null, propagated=false, idInSystem=XXX-12, systemName=MF_OMI, fields={field1=value1})>
when recursively comparing field by field, but found the following difference:

field/property '' differ:
- actual value   : SaveDataObjectCommand(id=MF_OMI:XXX-12, groupId=3ab62cd2-d924-4482-a986-d1e3dc2dcd22, propagated=false, idInSystem=XXX-12, systemName=MF_OMI, status=NEW, fields={field1=value1})
- expected value : DataObjectCreatedEvent(groupId=null, propagated=false, idInSystem=XXX-12, systemName=MF_OMI, fields={field1=value1})

The recursive comparison was performed with this configuration:
- the following fields were ignored in the comparison: id, groupId
- overridden equals methods were used in the comparison
- these types were compared with the following comparators:
  - java.lang.Double -> DoubleComparator[precision=1.0E-15]
  - java.lang.Float -> FloatComparator[precision=1.0E-6]
- actual and expected objects and their fields were compared field by field recursively even if they were not of the same type, this allows for example to compare a Person to a PersonDto (call strictTypeChecking(true) to change that behavior).
```

The test will pass if I ignore the differences (including the fields that do not exists in both objects) `.ignoringFields("id", "groupId", "status")`

**Comment by joel-costigliola** [comment] 2019-08-18 09:51
@Sam-Kruglov  thanks for reporting this, could you give us a reproducible failing test ? (including the `SaveDataObjectCommand` and `DataObjectCreatedEvent` classes).

**Comment by Sam-Kruglov** [comment] 2019-08-18 13:14
```
@Test
void bla() {
    class A {
        String a,b;
    }
    class B {
        String b,c;
    }
    A a = new A();
    a.a = "a";
    a.b = "b";
    B b = new B();
    b.b = "b";
    b.c = "c";
    assertThat(a).usingRecursiveComparison()
                 //uncomment this to pass the test
                 //.ignoringFields("a")
                 .isEqualTo(b);
}
```

**Comment by joel-costigliola** [comment] 2019-08-25 10:21
@Sam-Kruglov are you using the latest version (3.13.2) ?

In the latest version, when running your test the missing fields are reported, i.e. the one from the expected object not found in actual (`a` in your test).

`field/property '' differ:` is shown which might be a bit confusing, the `''` is the path to the field which is empty since the missing fields are related to the top level objects, I'll change that to `the top level actual and expected objects differ` (is that clearer ? if not, please suggest a better wording)

here's the error message extract:
```
field/property '' differ:
- actual value   : org.assertj.core.api.recursive.comparison.RecursiveComparisonAssert_isEqualTo_Test$1ObjectAB@e041f0c
- expected value : org.assertj.core.api.recursive.comparison.RecursiveComparisonAssert_isEqualTo_Test$1ObjectBC@6a175569
org.assertj.core.api.recursive.comparison.RecursiveComparisonAssert_isEqualTo_Test$1ObjectAB can't be compared to org.assertj.core.api.recursive.comparison.RecursiveComparisonAssert_isEqualTo_Test$1ObjectBC as ObjectBC does not declare all ObjectAB fields, it lacks these:[a]
```

here's the complete error message:

```
java.lang.AssertionError: 
Expecting:
  <org.assertj.core.api.recursive.comparison.RecursiveComparisonAssert_isEqualTo_Test$1ObjectAB@e041f0c>
to be equal to:
  <org.assertj.core.api.recursive.comparison.RecursiveComparisonAssert_isEqualTo_Test$1ObjectBC@6a175569>
when recursively comparing field by field, but found the following difference:

field/property '' differ:
- actual value   : org.assertj.core.api.recursive.comparison.RecursiveComparisonAssert_isEqualTo_Test$1ObjectAB@e041f0c
- expected value : org.assertj.core.api.recursive.comparison.RecursiveComparisonAssert_isEqualTo_Test$1ObjectBC@6a175569
org.assertj.core.api.recursive.comparison.RecursiveComparisonAssert_isEqualTo_Test$1ObjectAB can't be compared to org.assertj.core.api.recursive.comparison.RecursiveComparisonAssert_isEqualTo_Test$1ObjectBC as ObjectBC does not declare all ObjectAB fields, it lacks these:[a]

The recursive comparison was performed with this configuration:
- overridden equals methods were used in the comparison
- these types were compared with the following comparators:
  - java.lang.Double -> DoubleComparator[precision=1.0E-15]
  - java.lang.Float -> FloatComparator[precision=1.0E-6]
- actual and expected objects and their fields were compared field by field recursively even if they were not of the same type, this allows for example to compare a Person to a PersonDto (call strictTypeChecking(true) to change that behavior).
```

**Comment by joel-costigliola** [comment] 2019-09-01 06:16
@Sam-Kruglov I have finished implementing this, here's how the error is reported now:
```
java.lang.AssertionError: 
Expecting:
  <org.example.test.Test$1ObjectAB@6f45df59>
to be equal to:
  <org.example.test.Test$1ObjectBC@38e79ae3>
when recursively comparing field by field, but found the following difference:

Top level actual and expected objects differ:
- actual value   : org.example.test.Test$1ObjectAB@6f45df59
- expected value : org.example.test.Test$1ObjectBC@38e79ae3
org.example.test.Test$1ObjectAB can't be compared to org.example.test.Test$1ObjectBC as ObjectBC does not declare all ObjectAB fields, it lacks these: [a]

The recursive comparison was performed with this configuration:
- overridden equals methods were used in the comparison
- these types were compared with the following comparators:
  - java.lang.Double -> DoubleComparator[precision=1.0E-15]
  - java.lang.Float -> FloatComparator[precision=1.0E-6]
- actual and expected objects and their fields were compared field by field recursively even if they were not of the same type, this allows for example to compare a Person to a PersonDto (call strictTypeChecking(true) to change that behavior).
```
Hopefully this is clearer, feel free to suggest further improvements, I'm closing this issue but happy to reopen it.

**Closed by joel-costigliola** 2019-09-01 06:16 UTC
