### ISSUE TITLE
Bug: The commit for adding "AbstractStringAssert.isEqualTo(String string, Objects... param)" breaks existing unit tests

### ISSUE THREAD

**Issue by dscribellito** [joel-costigliola/assertj-core#1500] opened 2019-05-08 19:23 UTC
#### Summary

The following commit that added the AbstractStringAssert.isEqualTo(String string, Objects... param) method to AbstractStringAssert.java breaks existing unit tests that have "invalid format characters" in the string because it overrides the base class method and assumes that the parameter is now a formatted string: https://github.com/joel-costigliola/assertj-core/commit/37eacd11b0d4ef43c13d7d6c96dc7970ff2f5ffb

Note: I was using 3.11.1 and just upgraded to 3.12.2.

#### Example
This is an example test (in Kotlin) that now fails:
```
val encodedString = "foo bar+biz&baz*qux~qix/qax".urlEncode()
assertThat(encodedString).isEqualTo("foo%20bar%2Bbiz%26baz%2Aqux~qix%2Fqax")
```
with an exception like this:
```
java.util.UnknownFormatConversionException: Conversion = 'F'
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2691)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2720)
	at java.util.Formatter.parse(Formatter.java:2560)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.assertj.core.api.AbstractStringAssert.isEqualTo(AbstractStringAssert.java:312)
	at com.example.test.urlEncode_Always_ReturnsEncodedString(StringExtensionsTest.kt:43)
```

The current workaround is to cast the string to Any so that AbstractAssert.isEqualTo(Object expected) is the method that is actually invoked:
```
val encodedString = "foo bar+biz&baz*qux~qix/qax".urlEncode()
assertThat(encodedString).isEqualTo("foo%20bar%2Bbiz%26baz%2Aqux~qix%2Fqax" as Any)
```

**Comment by epeee** [comment] 2019-05-08 19:58
This one seems to be a duplicate of #1441, isn't it?
Good news, it is already fixed on master and will be part of 3.13.0.

**Comment by joel-costigliola** [comment] 2019-05-08 21:30
it is likely the case, @dscribellito can you make sure we fixed it by trying the current master version (just run `mvn install` to built it) and let us know if it was not fixed ?

**Comment by dscribellito** [comment] 2019-05-08 22:36
> it is likely the case, @dscribellito can you make sure we fixed it by trying the current master version (just run `mvn install` to built it) and let us know if it was not fixed ?

Yes, that does sound like the same issue actually. I can confirm that the fix currently checked into master does indeed address this issue. Thanks!

**Comment by joel-costigliola** [comment] 2019-05-08 23:10
@dscribellito  thanks for having taken the time to check, closing this as a duplicate.

**Closed by joel-costigliola** 2019-05-08 23:10 UTC
