### ISSUE TITLE
Add isEqualToNormalizingWhitespace and change isEqualToIgnoringWhitespace to really ignore all whitespace

### ISSUE THREAD

**Issue by sta-szek** [joel-costigliola/assertj-core#806] opened 2016-11-22 12:20 UTC
#### Summary
Assertion fails when comparing strings ignoring whitespaces (assertj 3.6.0)

#### Example

```java
assertThat("with white spaces").isEqualToIgnoringWhitespace("withwhitespaces");
```

**Comment by ptemplier** [comment] 2016-11-22 13:32
According to the documentation this is the expected behavior

from http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/AbstractCharSequenceAssert.html#isEqualToIgnoringWhitespace(java.lang.CharSequence)

```
Verifies that the actual CharSequence is equal to the given one, ignoring whitespace differences (mostly).
To be exact, the following whitespace rules are applied:

- all leading and trailing whitespace of both actual and expected strings are ignored
- any remaining whitespace, appearing within either string, is collapsed to a single space before comparison
```

**Comment by sta-szek** [comment] 2016-11-22 14:56
Ok, so is there any other method to remove all whitespaces and then compare both strings?
If not this is my feature request :)

**Comment by ptemplier** [comment] 2016-11-22 15:19
looks like it doesn't exist yet.

The hardest part would be to find the right name for this new method :-)

**Comment by sta-szek** [comment] 2016-11-23 06:14
I think `isEqualToIgnoringWhitespace` means: compare two strings and ignore whitespaces (more, whitechars)

But now the `isEqualToIgnoringWhitespace` method does: compare two strings ignoring whitespaces in front and at the end, but replace multiple whitespaces with single whitespace, only when they are in the middle of string.

So now method name lies. For me.

**Comment by PascalSchumacher** [comment] 2016-11-23 13:20
I agree that the method name is confusing. I guess `isEqualToNormalizingWhitespace` would be a better name for the existing method.

**Comment by joel-costigliola** [comment] 2016-11-23 20:14
In hindsight I agree that was a poor name, I like @PascalSchumacher idea so let's rename this assertion to `isEqualToNormalizingWhitespace` and make `isEqualToIgnoringWhitespace` really ignoring all whitespace.

**Comment by PascalSchumacher** [comment] 2016-11-27 11:52
I will try to submit a pull request for this.

**Comment by PascalSchumacher** [comment] 2017-01-01 10:36
I guess this can be closed, as my pull requests fixed it.

**Comment by joel-costigliola** [comment] 2017-01-02 04:20
indeed, thanks.

**Comment by karolmie1** [comment] 2017-02-15 08:36
Was This removed on the way? I am using: 

>     testCompile group: 'org.assertj', name: 'assertj-core', version: '3.6.2'

And I have same problem!

**Comment by joel-costigliola** [comment] 2017-02-15 09:13
Not sure what you mean but nothing has been removed yet, this change will be part of the next release 2.7.0/3.7.0.

**Comment by karolmie1** [comment] 2017-02-15 10:47
Oh, ok I thought that 2.7 was released long time ago, and now its 3.6, but it's just different branch. Sorry for interruption!

**Comment by joel-costigliola** [comment] 2017-02-15 21:40
In AssertJ 2.x versions target Java 7 while 3.x target Java 8, which means that 2.6 is way newer than 3.0 ! (might be a bit confusing but http://joel-costigliola.github.io/assertj/assertj-core-quick-start.html tries to clarify that).

**Comment by PascalSchumacher** [comment] 2017-05-08 16:13
I'm sorry everybody. Somehow this change/addition got lost on the way to 2.7.0 / 3.7.0. I could not figure out when/how. It will be in 2.8.0 / 3.8.0. Sorry again.

**Comment by joel-costigliola** [comment] 2017-05-08 21:21
@PascalSchumacher I don't know either but I likely screwed up this one.

**Comment by PascalSchumacher** [comment] 2017-05-17 21:23
@joel-costigliola Will this issue be part of 2.7.1?

**Comment by joel-costigliola** [comment] 2017-05-17 21:32
I feel it is more 2.8.0 as it is a breaking change which I'm happy to release instead of 2.7.1.
is this already in 2.x ? (I haven't looked at it thoroughly)

**Comment by PascalSchumacher** [comment] 2017-05-17 21:35
Yes is is already in 2.x and master. Just revert https://github.com/joel-costigliola/assertj-core/commit/feb09abe086250a4b3de0bc0a6f59d4d918da8a7 and https://github.com/joel-costigliola/assertj-core/commit/2154840a8f1586cc0a7e4a76bc4c13a0aed14c49

**Comment by joel-costigliola** [comment] 2017-05-17 21:48
I was thinking to skip 2.7.1 to release directly 2.8.0 (and move the other 2.8.0 issues to 2.9.0).
I have fixed the `isBetween` issue in 3.7.0, it turned out to be a bug for `Instant` but more a new feature for the other Temporal assertions, it makes sense to me to release also a 3.8.0 instead of 3.7.1.

**Comment by PascalSchumacher** [comment] 2017-05-17 21:51
Sure. :+1:

**Comment by PascalSchumacher** [comment] 2017-05-21 07:30
AssertJ versions 2.8.0 / 3.8.0 with include this change/addition have just been released. :smile:

**Closed by PascalSchumacher** 2017-05-21 07:30 UTC
Labels: new feature
