### ISSUE TITLE
as() and describedAs() are not working on raw object types 

### ISSUE THREAD

**Issue by falkoner** [joel-costigliola/assertj-core#485] opened 2015-09-07 19:38 UTC
Let's assume I have some object of type JSONObject:
```
JSONObject data;
// {"symbol":"AAPL","companyName":"Apple Inc"}
```

When I want to do any assertion on it providing as() or describedAs() it will complain about "cannot resolve containsKey()":
```
assertThat(data).as("JSON data object").containsKey("symbols");
```

So to make it work I use one of two options:

* remove description - assertThat(data).containsKey("symbols"); - this works as a charm, but will not render any useful description
* convert JSON Object to something understandable by AssertJ - assertThat(data.keySet().toArray()).as("JSON data object").contains("symbols");

I realize that AssertJ can't support all possible types, but do I have any better options in this case? See also https://github.com/joel-costigliola/assertj-core/issues/484 for related question.

**Comment by PascalSchumacher** [comment] 2015-10-27 18:35
Hi falkoner,

AssertJ does not work like that.

Even for types AssertJ knows about as() does not return the object. This does not compile:

```java
Description description = new Description() { public String value() { return "sdf"; }};
assertThat(new Date()).as(description).getClass().after(new Date());
```
because as() and describedAs() do not return the object, but a subclass of AbstractAssert, e.g.

```java
System.out.println(assertThat(new Date()).as(description).getClass());
```

prints "class org.assertj.core.api.DateAssert"

**Comment by joel-costigliola** [comment] 2015-10-31 08:23
@falkoner here's the problem:
- `JSONObject` is that is a raw map
- AssertJ `containsKey` uses generics to enforce type it but it does not know what type to expect, the cryptic compilation error actually expresses that.

This code should compile:
```java
    Map<Object, ?>  dataAsMap = data; // {"symbol":"AAPL","companyName":"Apple Inc"}
    Object o = "symbol";
    assertThat(data).as("ssss").containsKey(o);
```

**Comment by Holzberg** [comment] 2016-02-15 18:55
@joel-costigliola 

Map and List do not work with the as() method either.

This does not compile:
`Assertions.assertThat(map).as("").containsOnlyKeys("Key1","Key2")`

I don't understand @PascalSchumacher as the following returns the same object:
```
System.out.println(Assertions.assertThat(map));
System.out.println(Assertions.assertThat(map).as(""));
```
I thought maybe that as() only worked with primitves, but BigDecimal works.

Please do not just "close" this issue.  Either find a fix or update the documentation for the assertThat() methods that do not work with as() so others don't have to do the research that at least 2 of us have now done.  Lists and Maps are commonly used.

Thanks.

**Comment by joel-costigliola** [comment] 2016-02-16 20:47
I'll have another look at it after my holidays :-)

**Comment by joel-costigliola** [comment] 2016-02-20 19:32
Hmmm ... I can't reproduce the problem anymore, the following test is passing both in eclipse and maven:

```java
@Test
public void as_and_list_or_map() {
  List<Ring> elvesRings = newArrayList(vilya, nenya, narya);
  assertThat(elvesRings).as("abc").isNotEmpty();
  assertThat(elvesRings).as("abc").contains(vilya, atIndex(0));
  assertThat(elvesRings).as("abc %d %d", 1, 2).isNotEmpty();
  
  
  assertThat(ringBearers).as("map").hasSize(4); 
  assertThat(ringBearers).as("map %s", "size").hasSize(4); 
  assertThat(ringBearers).as("map %s", "keys").containsOnlyKeys(vilya, nenya, narya, oneRing); 
  assertThat(ringBearers).as("map").containsOnlyKeys(vilya, nenya, narya, oneRing); 

  Map<String, String> map =  ImmutableMap.of("Key1","Value1", "Key2","Value2");
  assertThat(map).as("").containsOnlyKeys("Key1","Key2");
}
```

I remember having troubles with some versions of JDK 8, the one that I'm using (fro maven) is:

```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T23:57:37+12:00)
Maven home: /home/joel/prog/apache-maven-3.3.3
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /home/joel/prog/jdk1.8.0_65/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-77-generic", arch: "amd64", family: "unix"
```

Can you tell me what environment are you using ?

**Comment by joel-costigliola** [comment] 2016-02-22 06:05
@Holzberg please let me know with which environment you are experiencing  the problem.

In absence of feedback, I will most certainly close this issue in a week or two ...

**Comment by Holzberg** [comment] 2016-02-22 16:48
@joel-costigliola  Sorry... I saw your message this weekend but my company's VPN was down and I could not get you the info.

I am using Notepad++ instead of Eclipse.

I am using AssertJ 3.3.0 and below is the output from "java -version".
```
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)
```

I looked at your code and noticed you were using specific types on your Maps. So I did some more testing and found out that if you don't specify your types, then AssertJ will not compile, but Java is OK with it.

This first block of code compile just fine.
```
Map<String, String> map2 = new java.util.HashMap<>();
map2.put("Key1","Value1");
map2.put("Key2","Value2");
Assertions.assertThat(map2).as("").containsOnlyKeys("Key1","Key2");
```

This second block does not compile.  Notice I am not specifying the Map type for map1.

```
Map map1 = new java.util.HashMap<>();
map1.put("Key1","Value1");
map1.put("Key2","Value2");
Assertions.assertThat(map1).as("").containsOnlyKeys("Key1","Key2");
```

This also does not work...

```
Map<?,?> map1 = new java.util.HashMap<>();
map1.put("Key1","Value1");
map1.put("Key2","Value2");
Assertions.assertThat(map1).as("").containsOnlyKeys("Key1","Key2");
```

**Comment by joel-costigliola** [comment] 2016-02-22 20:36
Interesting ... I'll see what I can do, thanks for taking the time to do more testing.

**Comment by Holzberg** [comment] 2016-02-22 20:50
No problem... thanks for taking the time to look into it :)

**Comment by joel-costigliola** [comment] 2016-02-23 09:16
My current understanding is that when a method is specifying generic parameters (like  `containsOnlyKeys`) and java does not know the generic type used in the calling object (like `map1`) it cannot fulfill the expected requirements and won't compile.

Interesingly, if you define `map1` as `Map<Object,?>` the following assertion compiles fine:
```java
Assertions.assertThat(map1).as("").containsOnlyKeys("Key1","Key2");
```

I will continue investigate but my gut feeling is that to solve this issue, AssertJ should get rid of generic parameters which I'm not sure most users would agree.

To be continued ...

**Comment by joel-costigliola** [comment] 2016-03-06 07:24
More feedback on the example with widlcard
```java
Map<?, ?> map1 = new java.util.HashMap<>();
map1.put("Key1", "Value1"); // COMPILE ERROR
map1.put("Key2", "Value2"); // COMPILE ERROR
assertThat(map1).containsOnlyKeys("Key1", "Key2"); // COMPILE ERROR
assertThat(map1).as("").containsOnlyKeys("Key1", "Key2"); // COMPILE ERROR
```
All the compilation errors comes from the fact that we don't know what is in `map1` thus we can't put or check anything from it.

I have fixed the behavior for raw Map and the following test now passes:
```java
@Test
public void raw_map_assertion_and_descirption_using_as() {
  Map map1 = new java.util.HashMap<>();
  map1.put("Key1", "Value1");
  map1.put("Key2", "Value2");
  assertThat(map1).as("").containsOnlyKeys("Key1", "Key2");
}
```

**Comment by joel-costigliola** [comment] 2016-03-06 07:50
BTW this will also address code using basic assertions before map ones, e.g. 
```java
assertThat(map1).isNotNull().containsOnlyKeys("Key1", "Key2"); 
```

**Comment by Holzberg** [comment] 2016-03-06 14:08
Awesome!  Thanks!

I'm not sure the extent of your fix as I have not upgraded, but it fails for all generic classes as the code below fails for me...

```
Set set1 = new java.util.HashSet<>();
set1.add("Value1");
set1.add("Value2");
Assertions.assertThat(set1).as("").containsOnly("Value1", "Value2");
// should be org.assertj.core.api.ListAssert@1
// compiler says: AbstractAssert

List list1 = new java.util.ArrayList<>();
list1.add("Value1");
list1.add("Value2");
Assertions.assertThat(list1).as("").containsOnly("Value1", "Value2");
// should be org.assertj.core.api.IterableAssert@1
// compiler says: AbstractAssert
```

Maybe you already addressed those as well since you did change the title of the issue..

**Comment by joel-costigliola** [comment] 2016-03-06 20:08
Yeah I know, every generic typed assertion will have the same pb.

**Closed** 2016-03-12 23:01 UTC
