### ISSUE TITLE
KafkaConditions value matching

### ISSUE THREAD

**Issue by shaunthomas999** [joel-costigliola/assertj-core#1366] opened 2018-11-27 15:41 UTC
#### Summary

I have some difficulty in matching two Kafka `ConsumerRecord`s using Assertj. Please see the example.

#### Example

```java
@Slf4j
@RunWith(SpringRunner.class)
@SpringBootTest
@DirtiesContext
public class KafkaProducerTests {

  private final static String TOPIC_NAME = "greeting-topic";

  @Autowired
  private KafkaProducer kafkaProducer;

  private KafkaMessageListenerContainer<String, Greeting> container;

  private BlockingQueue<ConsumerRecord<String, Greeting>> records;

  @ClassRule
  public static EmbeddedKafkaRule embeddedKafka = new EmbeddedKafkaRule(1, true, TOPIC_NAME);

  @Before
  public void setUp() throws Exception {

    Map<String, Object> consumerProperties = KafkaTestUtils.consumerProps("greeting-group", "false", embeddedKafka.getEmbeddedKafka());
    val consumerFactory = new DefaultKafkaConsumerFactory<String, Greeting>(consumerProperties);
    val containerProperties = new ContainerProperties(TOPIC_NAME);
    container = new KafkaMessageListenerContainer<>(consumerFactory, containerProperties);

    // create a thread safe queue to store the received message
    records = new LinkedBlockingQueue<>();

    // setup a Kafka message listener
    container
        .setupMessageListener(new MessageListener<String, Greeting>() {
          @Override
          public void onMessage(
              ConsumerRecord<String, Greeting> record) {
            log.info("test-listener received message='{}'", record.toString());
            records.add(record);
          }
        });

    // start the container and underlying message listener
    container.start();

    // wait until the container has the required number of assigned partitions
    ContainerTestUtils.waitForAssignment(container, embeddedKafka.getEmbeddedKafka().getPartitionsPerTopic());
  }

  @After
  public void tearDown() {
    // stop the container
    container.stop();
  }

  @Test
  public void testSendMessageSuccessfully() throws Exception {
    Greeting greeting = new Greeting("Hello Shaun!", "Shaun");
    kafkaProducer.sendMessage(TOPIC_NAME, greeting);

    // check that the message was received
    ConsumerRecord<String, Greeting> received = records.poll(10, TimeUnit.SECONDS);

    // AssertJ Condition to check the value
     assertThat(received).has(value(greeting));
  }
}
```

The assert statement in third last line is giving me following error:

```
java.lang.AssertionError: 
Expecting:
 <ConsumerRecord(topic = greeting-topic, partition = 1, offset = 0, CreateTime = 1543332496418, serialized key size = -1, serialized value size = 37, headers = RecordHeaders(headers = [RecordHeader(key = __TypeId__, value = [99, 111, 109, 46, 115, 104, 97, 117, 110, 116, 104, 111, 109, 97, 115, 57, 57, 57, 46, 107, 97, 102, 107, 97, 46, 109, 111, 100, 101, 108, 46, 71, 114, 101, 101, 116, 105, 110, 103])], isReadOnly = false), key = null, value = {"msg":"Hello Shaun!","name":"Shaun"})>
to have:
 <a ConsumerRecord with 'value' Greeting(msg=Hello Shaun!, name=Shaun)>
```

How can I match two `ConsumerRecord` using Assertj?

**Comment by joel-costigliola** [comment] 2018-11-27 20:31
What does you Condition looks like ?
It looks like you are trying to compare a map to a Greeting ...

**Comment by joel-costigliola** [comment] 2019-03-03 10:28
@shaunthomas999 I'm closing this issue but I'm happy to reopen if you can provide us a test case reproducing it.

**Closed by joel-costigliola** 2019-03-03 10:28 UTC
