### ISSUE TITLE
Javadoc example for isXmlEqualTo() fails due to whitespace differences

### ISSUE THREAD

**Issue by Thunderforge** [joel-costigliola/assertj-core#1396] opened 2019-01-15 17:20 UTC
#### Summary
The [Javadoc for [`isXmlEqualTo()`](http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/AbstractCharSequenceAssert.html#isXmlEqualTo(java.lang.CharSequence)) includes an example that demonstrates how it works by ignoring whitespace. In particular, the code example includes this comment

     // No matter how your xml string is formated, isXmlEqualTo is able to compare it's content with another 

However, running the code results in assertion failures due to differences in whitespace. Thus the actual behavior does not match that of the Javadoc.

Because differences in whitespace are common, I would like for this to be fixed so that the actual behavior matches that of the Javadoc. Alternatively, it would be acceptable to make it so the user can have a choice between the behaviors.

#### Example

```java
 String expectedXml =
     "<rings>\n" +
         "  <bearer>\n" +
         "    <name>Frodo</name>\n" +
         "    <ring>\n" +
         "      <name>one ring</name>\n" +
         "      <createdBy>Sauron</createdBy>\n" +
         "    </ring>\n" +
         "  </bearer>\n" +
         "</rings>";
 
 // No matter how your xml string is formated, isXmlEqualTo is able to compare it's content with another xml String.
 String oneLineXml = "<rings><bearer><name>Frodo</name><ring><name>one ring</name><createdBy>Sauron</createdBy></ring></bearer></rings>";
 assertThat(oneLineXml).isXmlEqualTo(expectedXml);
 
 String xmlWithNewLine =
     "<rings>\n" +
         "<bearer>   \n" +
         "  <name>Frodo</name>\n" +
         "  <ring>\n" +
         "    <name>one ring</name>\n" +
         "    <createdBy>Sauron</createdBy>\n" +
         "  </ring>\n" +
         "</bearer>\n" +
         "</rings>";
 assertThat(xmlWithNewLine).isXmlEqualTo(expectedXml);
 
 // You can compare it with oneLineXml
 assertThat(xmlWithNewLine).isXmlEqualTo(oneLineXml);
```

All of these assertions fail due to differences in whitespace. There is also a file assert, but without that file, I can't test it.

**Comment by dev-priporov** [comment] 2019-01-20 08:37
Hi @Thunderforge  , I've tried to reproduce, but asserts from the example for me secceeded, so I can't reproduce that. Could you please provide a simple git project with the issue?

**Comment by Thunderforge** [comment] 2019-01-23 20:43
@dev-priporov I'm still trying to get a self-contained code example. In our proprietary project, it fails 100% of the time, but in a fresh project, it passes 100% of the time.

Looking deeper into the code, [this line](https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/internal/Strings.java#L984) returns XML indented with two spaces in my full project, but indented with four spaces in the fresh project. In the following line, there is an exact comparison, so it fails due to different indentation. I'm still trying to figure out *why* it indents differently between the two projects.

**Comment by PascalSchumacher** [comment] 2019-01-23 20:58
I guess both projects have different DOM implementations on the classpath:

https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/util/xml/XmlStringPrettyFormatter.java#L51

But as Joel said you should really use `xmlunit-assertj` for XML testing. https://github.com/xmlunit/xmlunit can easily be configured to ignore whitespace differences.

**Comment by joel-costigliola** [comment] 2019-03-03 10:01
@Thunderforge I'm closing this issue but if you find a way to reproduce it I'll reopen it.

**Closed by joel-costigliola** 2019-03-03 10:01 UTC

**Comment by bcalmac** [comment] 2020-10-08 00:37
We have run into the same problem in our project. This time it's tabs vs spaces. It works for some people and it doesn't for others. I think it would make sense to deprecate the method, document that the use of XML assertions is discouraged and point people to XML unit.

**Comment by joel-costigliola** [comment] 2020-10-08 00:53
Yep, fair enough, will do.
