### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/tools/ant/Task;

### ISSUE THREAD

**Issue by vanniktech** [joel-costigliola/assertj-core#1053] opened 2017-08-08 15:16 UTC
#### Summary

Starting with the new Android Support Testing libraries Test Runner 1.0.0 and Espresso 3.0.0, classes that are referenced but not on the classpaths are no longer allowed and will crash the app during start up with a NoClassDefFoundError.

This is the case when using assertj2 (`org.assertj:assertj-core:2.8.0`). It'll fail with: 

```
E  Fatal exception when running tests
E  java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/tools/ant/Task;
E      at java.lang.Class.classForName(Native Method)
E      at java.lang.Class.forName(Class.java:453)
E      at android.support.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:76)
E      at android.support.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
E      at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:808)
E      at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:481)
E      at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:367)
E      at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2074)
E  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.tools.ant.Task" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zipfile "/data/app/com.myapp.android.bluetoothsdk.test-7Vrra_PX2nOifJ1I5oa-GQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp.android.bluetoothsdk.test-7Vrra_PX2nOifJ1I5oa-GQ==/lib/arm64, /system/lib64, /vendor/lib64]]
E      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
E      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E      ... 8 more
```

Could this somehow get fixed?

**Comment by PascalSchumacher** [comment] 2017-08-08 21:22
Thanks for reporting!

Sadly I lack android experience, but are you sure this error is caused by AssertJ? AssertJ does not have a dependency on any Ant classes and I do not see any AssertJ classes in the stacktrace. Try adding Apache Ant to the classpath.

**Comment by vanniktech** [comment] 2017-08-08 22:23
Yup. The moment I remove the dependencies everything works. I'll try adding the class tomorrow and start to investigate this further.

**Comment by joel-costigliola** [comment] 2017-08-10 08:38
closing this but @vanniktech feel free to comment if you think it should be reopened.

**Closed by joel-costigliola** 2017-08-10 08:38 UTC

**Comment by vanniktech** [comment] 2017-08-12 09:01
As stated above the error went away when removing the dependency on `assertj2`. I ended up switching to festassert as I don't believe adding ant as a dependency which should not be needed is the right solution.

**Comment by joel-costigliola** [comment] 2017-08-12 10:33
@vanniktech assertj 2.x does not have any dependencies as shown here: https://mvnrepository.com/artifact/org.assertj/assertj-core/2.8.0

**Comment by caipivara** [comment] 2017-11-22 22:59
@joel-costigliola This is happening with me too using version `2.8.0`

**Comment by joel-costigliola** [comment] 2017-11-23 00:27
@caipivara as I said assertj-core has no dependencies, here's an example of a project using assertj, note that there is no dependencies coming from assertj:
```
[INFO] ------------------------------------------------------------------------
[INFO] Building elastic-search-test 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ elastic-search-test ---
[INFO] com.orchestral.sdp:elastic-search-test:jar:1.0
[INFO] +- org.assertj:assertj-core:jar:3.8.0:test
[INFO] +- org.apache.logging.log4j:log4j-api:jar:2.9.1:test
[INFO] +- org.apache.logging.log4j:log4j-core:jar:2.9.1:test
[INFO] \- org.elasticsearch.test:framework:jar:5.6.4:test
[INFO]    +- org.elasticsearch.client:elasticsearch-rest-client:jar:5.6.4:test
[INFO]    |  +- org.apache.httpcomponents:httpasyncclient:jar:4.1.2:test
[INFO]    |  \- org.apache.httpcomponents:httpcore-nio:jar:4.4.5:test
[INFO]    +- org.elasticsearch:elasticsearch:jar:5.6.4:test
[INFO]    |  +- org.apache.lucene:lucene-core:jar:6.6.1:test
[INFO]    |  +- org.apache.lucene:lucene-analyzers-common:jar:6.6.1:test
[INFO]    |  +- org.apache.lucene:lucene-backward-codecs:jar:6.6.1:test
```

Having said if you want to double check if there are any dependencies sneaking in, try to exclude AssertJ test dependencies as shown in https://mvnrepository.com/artifact/org.assertj/assertj-core/2.8.0 and see it that solves the problem.

Be sure also to only use Java6 Assertions classes as mentioned in http://joel-costigliola.github.io/assertj/assertj-core.html#android.

Finally AssertJ does not officially support Android, it's kind of a best effort (I don't have Android expertise myself), we are happy though to incorporate any fixes/improvements from the community.
