### ISSUE TITLE
v3.0.0 - usingFieldByFieldElementComparator - polymorphic collection - org.assertj.core.util.introspection.IntrospectionError

### ISSUE THREAD

**Issue by rcusters** [joel-costigliola/assertj-core#399] opened 2015-05-04 11:01 UTC
When using usingFieldByFieldElementComparator on a collection containing different types a IntrospectionError is thrown. 
This worked with version 1.6.1

Example: 

    import org.assertj.core.api.Assertions;
    import org.junit.Test;
    
    import java.util.ArrayList;
    import java.util.List;
    
    public class UsingFieldByFieldElementComparatorTest {
    
        @Test
        public void usingFieldByFieldElementComparatorTest() throws Exception {
            List<Animal> animals = new ArrayList<>();
            Bird bird = new Bird("White");
            Snake snake = new Snake(15);
            animals.add(bird);
            animals.add(snake);
    
            Assertions.assertThat(animals)
                    .usingFieldByFieldElementComparator()
                    .containsExactly(bird, snake);
        }
    
        private class Animal {
            private final String name;
    
            private Animal(String name) {
                this.name = name;
            }
    
            public String getName() {
                return name;
            }
        }
    
        private class Bird extends Animal {
            private final String color;
    
            private Bird(String color) {
                super("Bird");
                this.color = color;
            }
    
            public String getColor() {
                return color;
            }
        }
    
        private class Snake extends Animal {
            private final int length;
    
            private Snake(int length) {
                super("Snake");
                this.length = length;
            }
    
            public int getLength() {
                return length;
            }
        }
    }

org.assertj.core.util.introspection.IntrospectionError: Unable to obtain the value of <'color'> field/property from <UsingFieldByFieldElementComparatorTest$Snake@5a61f5df>, expecting a public field or getter
	at org.assertj.core.internal.Objects.getFieldOrPropertyValue(Objects.java:683)
	at org.assertj.core.internal.Objects.isEqualToIgnoringGivenFields(Objects.java:636)
	at org.assertj.core.internal.Objects.areEqualToIgnoringGivenFields(Objects.java:727)
	at org.assertj.core.internal.FieldByFieldComparator.areEqual(FieldByFieldComparator.java:36)
	at org.assertj.core.internal.FieldByFieldComparator.compare(FieldByFieldComparator.java:32)
	at org.assertj.core.internal.ComparatorBasedComparisonStrategy.iterableContains(ComparatorBasedComparisonStrategy.java:65)
	at org.assertj.core.internal.Iterables.iterableContains(Iterables.java:235)
	at org.assertj.core.internal.Iterables.setFromIterable(Iterables.java:314)
	at org.assertj.core.internal.Iterables.assertContainsExactly(Iterables.java:915)
	at org.assertj.core.api.AbstractIterableAssert.containsExactly(AbstractIterableAssert.java:154)
	at UsingFieldByFieldElementComparatorTest.usingFieldByFieldElementComparatorTest(UsingFieldByFieldElementComparatorTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by joel-costigliola** [comment] 2015-05-04 21:01
It's a bug, thanks for reporting this with a test case.
Cheers

**Comment by dorzey** [comment] 2015-05-05 14:25
I've taken a quick look at this and I think I've understood why this doesn't work in the latest version and why it does in 1.6.1.

In the latest version, we end up comparing a Bird with a Snake; but for some reason, that I'm yet to identify, this situation does not happen in 1.6.1. Does anybody have any pointers?

It's also worth noting that the tests in IterableAssert_usingFieldByFieldElementComparator_Test extends IterableAssertBaseTest have only Lists containing objects of the same type.

**Comment by joel-costigliola** [comment] 2015-05-05 22:46
We definitely should add some tests for heterogeneous lists.

I haven't done a thorough investigation but one of the problem is that `Iterables.iterableContains` and `Iterables.areEqual` should never fail because objects can't be compared, instead we should just return `false`, this can be fixed by catching any exception in `IterableElementComparisonStrategy.areEqual`.

**Comment by dorzey** [comment] 2015-05-06 12:58
The `IterableElementComparisonStrategy` is not being called in this case. The `FieldByFieldComparator` is so we end up in `Objects.isEqualToIgnoringGivenFields`; if we catch the `IntrospectionError` inside this method then there are test failures:
* `FieldByFieldComparator_compareTo_Test.should_throw_exception_if_Objects_have_not_the_same_properties`
* `IgnoringFieldsComparator_compareTo_Test.should_throw_exception_if_Objects_have_not_the_same_properties`

I've added the test to highlight the issue here: https://github.com/dorzey/assertj-core/commits/issue_399

**Comment by joel-costigliola** [comment] 2015-05-06 17:29
You're right this was obviously was `FieldByFieldComparator`.

I think these tests and the current implementation of `FieldByFieldComparator` are bad, they should just check that objects are not equal but not throw any exceptions. 

Same pb with and `OnFieldsComparator`.

**Comment by joel-costigliola** [comment] 2015-05-07 10:43
@dorzey do you plan to fix this ? otherwise I'm taking it.

**Comment by dorzey** [comment] 2015-05-07 12:07
I can take it; should hopefully have time to finish it this weekend.

I'll catch the `IntrospectionException` inside `FieldByFieldComparator.areEqaul` and `OnFieldsComparator.areEqual` so they can return false; leaving `Objects.isEqualToIgnoringGivenFields` untouched.

**Comment by joel-costigliola** [comment] 2015-05-10 02:02
Thanks @dorzey for the contribution !

**Closed** 2015-05-10 02:01 UTC
Labels: bug
