### ISSUE TITLE
isInstanceOf() should narrow the returned assertion type

### ISSUE THREAD

**Issue by kriegfrj** [joel-costigliola/assertj-core#1109] opened 2017-11-07 00:10 UTC
#### Summary

This is related to the concept behind #1108.

At the moment, 
It would be handy if `AbstractAssert.isInstanceOf()` assertion could narrow the return type to return the most specific assertion class available.

#### Example

Current example (slightly contrived, but illustrates the point):
```java
// Code under test
Object obj = "This is a test";

// Test code
assertThat(obj).isInstanceOf(String.class);

String str = (String)obj;
assertThat(str).hasLength(14);
```

At the moment, AbstractAssert.isInstanceOf() returns the assertion's SELF type. So because the first `assertThat()` is called on a reference variable of type `Object`, the compiler will expect `isInstanceOf()` to return an `ObjectAssert`. Of course, this class doesn't have the String-specific assertions that I would like to do, so having now established that it is in fact a String I would like to do String-specific assertions on it. Hence the need to cast. I find that this is a pattern that occurs frequently in my testing (particularly using legacy interfaces that don't use genericised return values to help get around this problem at compile time).

A simple workaround would be to define a method as follows (which I've done in my own code), very similar to `catchThrowableOfType()`:

```java
@SuppressWarnings("unchecked")
public static <T> T assertAndCast(Object actual, Class<T> type) {
  assertThat(actual).isInstanceOf(type);
  return (T)actual;
}

// Test code
String str = assertAndCast(obj, String.class);
assertThat(str).hasLength(14);
```

However, a syntactically nicer solution (though much more difficult to implement) would be the following:

```java
// Test code
assertThat(obj)
  .isInstanceOf(String.class)
  .hasLength(14);
```
In order for this to work, `AbstractAssert.isInstanceOf()` must return a StringAssert instead of the self type when called with a Class<String> parameter.

This could be done by adding corresponding `isInstanceOf()` methods to `Assert` and `Abstract` assert for every known assertion type (similar to all the `assertThat()` methods), eg:

```java
public StringAssert isInstanceOf(Class<? extends String> type) {
  isInstanceOf((Class<Object>)type);
  return new StringAssert(actual);
}
public ListAssert isInstanceOf(Class<? extends List> type) {
  isInstanceOf((Class<Object>)type);
  return new ListAssert(actual);
}
```

The same principle could also apply to methods like `isSameAs()`:
```java
public StringAssert isSameAs(String expected) {
  isSameAs((Object)expected);
  return new StringAssert(actual);
}
public ListAssert isSameAs(List expected) {
  isSameAs((Object)expected);
  return new ListAssert(actual);
}
```

Of course, it would become a bit unwieldy trying to maintain all of these methods; it would make sense to have automatic code generator do this at compile time (it could also automatically generate all of the assertThat() methods in Assertions/AssertionsForClassTypes/AssertionsForInterfaceTypes). The disadvantage of generating them at compile time is that you wouldn't be able to add your custom assertion types into the hierarchy. I can't see an easy way around this other than having a custom classloader that can add the methods at load time, or maybe by having your custom deployment define its own versions of `Assert.java` and `AbstractAssert.java` and having them earlier in the class path. Even then, you'd need to convince your IDE to load the classes through your custom classloader in order for it to work, and I'm not sure how simple that would be.

#### Java 8 specific ?

I'm not sure if any attempt to implement this might fall foul of the same issues that required the split out into `AssertionsForClassTypes` and `AssertionsForInterfaceTypes` in Java 8.

**Comment by kriegfrj** [comment] 2017-11-07 00:41
I've just been digging a little further, and wanted to add a couple of things:

- I noticed `Assert` already has `asList()` and `asString()`, which are a limited implementation of this concept. 
- There are a series of other assertions that could all benefit from the same treatment as `isInstanceOf()`: `isExactlyInstanceOf()`, `hasSameClassAs()`, `isInstanceOfSatisifying()`.

**Comment by wimdeblauwe** [comment] 2018-03-13 14:21
Isn't this a duplicate of https://github.com/joel-costigliola/assertj-core/issues/683 ?

**Comment by joel-costigliola** [comment] 2018-03-13 20:41
@wimdeblauwe  kind of but the suggested approach here is to generate code. the thing is that it will bloat the API with a bunch of `isInstance` which will make it difficult discovering other assertions.

**Comment by wimdeblauwe** [comment] 2018-03-14 07:14
Indeed. That is why I think what is done in #683 is the best approach. But Googling showed this issue first for me and if I had not looked further I would have thought there was no solution yet. But there is a good one explained in that other issue, so I wanted to link them :-)

**Comment by scordio** [comment] 2019-04-28 15:38
> This could be done by adding corresponding `isInstanceOf()` methods to `Assert` and `Abstract` assert for every known assertion type (similar to all the `assertThat()` methods), eg:
> 
> ```java
> public StringAssert isInstanceOf(Class<? extends String> type) {
>   isInstanceOf((Class<Object>)type);
>   return new StringAssert(actual);
> }
> public ListAssert isInstanceOf(Class<? extends List> type) {
>   isInstanceOf((Class<Object>)type);
>   return new ListAssert(actual);
> }
> ```

Although this would be the cleanest solution, it cannot work due to type erasure. All methods would have the same signature and returning narrowed assertions would not be possible since the returning type is not part of the signature.

> I noticed `Assert` already has `asList()` and `asString()`, which are a limited implementation of this concept.

Extending this pattern would be an existing option to avoid the type erasure limitation.

Another option if we want to keep the same method name would be to [use placeholder parameters](https://michid.wordpress.com/2010/05/30/working-around-type-erasure-ambiguities/). In this case we would have a group of methods like:

```java
public AbstractStringAssert<?> instanceOf(String ignored) {
    objects.assertIsInstanceOf(info, actual, String.class);
    return Assertions.assertThat((String) actual);
}

public AbstractIntegerAssert<?> instanceOf(Integer ignored) {
    objects.assertIsInstanceOf(info, actual, Integer.class);
    return Assertions.assertThat((int) actual);
  }
```

The downside of both the approaches above is they would bloat the API: supporting all the known types (at least the same as `Assertions.assertThat()`) would create a bunch of entries during code completion (also mentioned in https://github.com/joel-costigliola/assertj-core/issues/683#issuecomment-250891973).

### My Proposal
I am not sure if there is another option for a type conversion API other than adding a bunch of methods for it.

Assuming this is the choice, to address the _too many entries for code completion_ issue, all these methods could be hidden behind lambdas. Specifically, `AbstractAssert` could just provide a new `instanceOf` method:

```java
public <T extends Assert<?,?>> T instanceOf(Function<? super ACTUAL, T> instanceOfProvider) {
    return instanceOfProvider.apply(actual);
}
```

and lambdas for the known types could be provided separately:

```java
public interface InstanceOfProviders {

  Function<Object, AbstractStringAssert<?>> STRING = actual -> {
    Assertions.assertThat(actual).isInstanceOf(String.class);
    return Assertions.assertThat((String) actual);
  };

  Function<Object, AbstractIntegerAssert<?>> INTEGER = actual -> {
    Assertions.assertThat(actual).isInstanceOf(Integer.class);
    return Assertions.assertThat((Integer) actual);
  };

  Function<Object, ClassAssert> CLASS = actual -> {
    Assertions.assertThat(actual).isInstanceOf(Class.class);
    return Assertions.assertThat((Class) actual);
  };

}
```

So the client code would look like (using static imports):

```java
assertThat((Object) 0).instanceOf(INTEGER).isZero();
assertThat((Object) "asd").instanceOf(STRING).contains("sd");
assertThat((Object) java.security.Certificate.class).instanceOf(CLASS).hasAnnotations(Deprecated.class);
```

Also, the client code would be free to define its own `instanceOf` provider lambdas.

Would this make sense?

**Comment by joel-costigliola** [comment] 2019-04-28 21:42
That is an interesting idea, I think https://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AssertFactory.html can be used as the `instanceOf` parameter.

@scordio are you willing to write a POC PR with a few instance providers just to get a better feel of what it will look like ?

**Comment by scordio** [comment] 2019-04-29 06:02
@joel-costigliola definitely, and thanks for the pointer!

**Comment by scordio** [comment] 2019-08-18 08:05
Hi @kriegfrj, could you check if [`asInstanceOf`](https://assertj.github.io/doc/#assertj-core-3.13.0-asInstanceOf) satisfies your requirements?

**Comment by kriegfrj** [comment] 2019-08-19 00:33
Hi @scordio ,

Thanks for your efforts on this!

I've had a brief look and I think what you've put together will work well. It looks a bit more like a Truth pattern than an AssertJ pattern - perhaps they will end up converging at some point in the future. :smile:

**Comment by scordio** [comment] 2019-08-30 00:41
Thanks for the feedback @kriegfrj! Then I will close this issue.

**Closed by scordio** 2019-08-30 00:41 UTC
